spring:
  sql:    init:      enabled: true
      continue-on-error: true
      platform: postgresql
      
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?schema=public
    username: postgres
    password: postgres
  application:
    name: projeto-covid
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none

server:
  port: 8080
  error:
    include-stacktrace: on-param